name:    wolf-web-server
version: "0.0.0.0"


dependencies:
- base >= 4.9 && < 5

library:
  dependencies:
  - async
  - bytestring
  - case-insensitive
  - conduit-extra
  - containers
  - data-default
  - http-client
  - http-types
  - mtl
  - optparse-applicative >=0.13 && <0.15
  - path
  - path-io
  - process
  - servant-server
  - shakespeare
  - template-haskell
  - text
  - time
  - transformers
  - unix
  - wai
  - wai-extra
  - wai-git-http
  - warp
  - wolf-api
  - wolf-data
  - wolf-server
  - yesod
  - yesod-auth
  - yesod-core
  - yesod-form
  - yesod-static
  source-dirs: src
  default-extensions: NoImplicitPrelude

executables:
  wolf-web-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolf-web-server

tests:
  wolf-web-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity
    - genvalidity-hspec
    - hspec
    - mtl
    - path
    - path-io
    - wolf-api
    - wolf-data
    - wolf-server
    - wolf-web-server
    - wolf-test-utils
    - yesod-test
