language: c
sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
  - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
  - stack setup
  - stack build --only-snapshot
  - stack install hindent
  - stack install cabal-install
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

script:
  - git --version
  - stack --version
  - ./zift.hs run
