packages:
- wolf-api
- wolf-cli
- wolf-client
- wolf-cub
- wolf-data
- wolf-google
- wolf-server
- wolf-web-server
- wolf-test-utils

extra-deps:
- servant-quickcheck-0.0.2.4
- sockaddr-0.0.0
- wai-git-http-0.0.0

resolver: lts-10.0
