packages:
- wolf-api
- wolf-cli
- wolf-client
- wolf-cub
- wolf-data
- wolf-server
- wolf-test-utils
extra-deps:
- genvalidity-0.3.2.0
- genvalidity-bytestring-0.0.0.1
- genvalidity-containers-0.2.0.1
- genvalidity-hspec-0.3.1.0
- genvalidity-hspec-aeson-0.0.1.1
- genvalidity-path-0.1.0.0
- genvalidity-time-0.0.0.2
- genvalidity-text-0.3.1.1
- validity-0.3.3.0
- validity-containers-0.1.0.3
- validity-bytestring-0.1.0.1
- validity-path-0.1.0.1
- validity-time-0.0.0.1
- validity-text-0.1.2.1
- servant-quickcheck-0.0.2.4
resolver: lts-8.17
