name: wolf-cub
version: '0.0.0.0'
category: CsSyd
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
library:
  source-dirs: src/
  default-extensions:
  - NoImplicitPrelude
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Cub
  - Wolf.Cub.Draw
  - Wolf.Cub.Handle
  - Wolf.Cub.OptParse
  - Wolf.Cub.OptParse.Types
  - Wolf.Cub.PropertyEditor
  - Wolf.Cub.PropertyEditor.Cursor
  - Wolf.Cub.SearchBox
  - Wolf.Cub.Types
  dependencies:
  - brick >=0.24 && <0.25
  - mtl
  - optparse-applicative
  - safe >=0.3 && <0.4
  - text >=1.2 && <1.3
  - time >=1.6 && <1.7
  - vector >=0.11 && <0.12
  - vty >=5.15 && <5.16
  - wolf-cli
  - wolf-data
executables:
  cub:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolf-cub
