name: wolf-client
version: '0.0.0.0'
category: CsSyd
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.9 && <=5
- servant >=0.9 && <0.10
- servant-client >=0.9 && <0.10
- text >=1.2 && <1.3
- wolf-api >=0.0 && <0.1
- wolf-data >=0.0 && <0.1
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Client
