name: wolf-api
version: '0.0.0.0'
category: CsSyd
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.9 && <=5
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Wolf.API
  dependencies:
  - aeson
  - base16-bytestring >=0.1 && <0.2
  - bcrypt >=0.0 && <0.1
  - bytestring >=0.10 && <0.11
  - containers >=0.5 && <0.6
  - mtl >=2.2 && <2.3
  - path >=0.6 && <0.7
  - path-io >=1.3 && <1.4
  - servant >=0.11 && <0.12
  - text >=1.2 && <1.3
  - typed-uuid >=0.0 && <0.1
  - uuid >=1.3 && <1.4
  - validity >=0.4 && <0.5
  - validity-bytestring >=0.2 && <0.3
  - validity-containers >=0.2 && <0.3
  - validity-text >=0.2 && <0.3
  - validity-time >=0.1 && <0.2
  - wolf-data >=0.0 && <0.1
tests:
  wolf-api-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - hspec
    - http-client >=0.5 && <0.6
    - mtl
    - path
    - path-io
    - servant
    - text
    - wai
    - warp
    - wolf-api
    - wolf-test-utils
    - wolf-data
