name: wolf-data-baked
version: '0.0.0.0'
category: People
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.9 && <=5
- bytestring
- containers
- deepseq
- mtl
- path
- path-io
- text
- typed-uuid
- validity
- validity-bytestring
- validity-containers
- validity-path
- validity-text
- validity-time
- validity-uuid
- wolf-data
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Data.Baked
tests:
  wolf-data-baked-test:
    main: Spec.hs
    source-dirs: test/
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base >=4.9 && <=5
    - bytestring
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-path
    - genvalidity-text
    - genvalidity-time
    - genvalidity-uuid
    - hspec
    - text
    - wolf-data-baked
    - wolf-test-utils

